"""Initial schema for AlgoLab DAA system

Revision ID: 89c110c6e2e7
Revises: 
Create Date: 2026-09-02 22:16:56.162007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89c110c6e2e7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('algorithms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('paradigm', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('pseudocode', sa.Text(), nullable=True),
    sa.Column('implementation_python', sa.Text(), nullable=True),
    sa.Column('best_case', sa.String(length=50), nullable=False),
    sa.Column('average_case', sa.String(length=50), nullable=False),
    sa.Column('worst_case', sa.String(length=50), nullable=False),
    sa.Column('space_complexity', sa.String(length=50), nullable=False),
    sa.Column('recurrence_relation', sa.String(length=200), nullable=True),
    sa.Column('is_stable', sa.Boolean(), nullable=True),
    sa.Column('is_in_place', sa.Boolean(), nullable=True),
    sa.Column('is_adaptive', sa.Boolean(), nullable=True),
    sa.Column('is_deterministic', sa.Boolean(), nullable=True),
    sa.Column('advantages', sa.JSON(), nullable=True),
    sa.Column('disadvantages', sa.JSON(), nullable=True),
    sa.Column('suitable_cases', sa.JSON(), nullable=True),
    sa.Column('unsuitable_cases', sa.JSON(), nullable=True),
    sa.Column('daa_concept_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_algorithms_category'), 'algorithms', ['category'], unique=False)
    op.create_index(op.f('ix_algorithms_name'), 'algorithms', ['name'], unique=False)
    op.create_index(op.f('ix_algorithms_paradigm'), 'algorithms', ['paradigm'], unique=False)
    op.create_index(op.f('ix_algorithms_slug'), 'algorithms', ['slug'], unique=True)
    op.create_table('problems',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('paradigm', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('input_format', sa.Text(), nullable=False),
    sa.Column('output_format', sa.Text(), nullable=False),
    sa.Column('constraints', sa.Text(), nullable=True),
    sa.Column('data_type', sa.String(length=50), nullable=True),
    sa.Column('example_input', sa.JSON(), nullable=True),
    sa.Column('example_output', sa.JSON(), nullable=True),
    sa.Column('daa_topics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problems_category'), 'problems', ['category'], unique=False)
    op.create_index(op.f('ix_problems_name'), 'problems', ['name'], unique=False)
    op.create_index(op.f('ix_problems_slug'), 'problems', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('algorithm_problem_mappings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('algorithm_id', sa.String(length=36), nullable=False),
    sa.Column('problem_id', sa.String(length=36), nullable=False),
    sa.Column('suitability_score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['algorithm_id'], ['algorithms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datasets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('problem_type', sa.String(length=100), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('distribution', sa.String(length=100), nullable=True),
    sa.Column('random_seed', sa.Integer(), nullable=True),
    sa.Column('characteristics', sa.JSON(), nullable=True),
    sa.Column('data_payload', sa.JSON(), nullable=False),
    sa.Column('preview_sample', sa.JSON(), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('problem_id', sa.String(length=36), nullable=False),
    sa.Column('algorithm_ids', sa.JSON(), nullable=False),
    sa.Column('input_sizes', sa.JSON(), nullable=False),
    sa.Column('dataset_distribution', sa.String(length=100), nullable=True),
    sa.Column('repetitions', sa.Integer(), nullable=True),
    sa.Column('results_summary', sa.JSON(), nullable=True),
    sa.Column('asymptotic_fit_summary', sa.JSON(), nullable=True),
    sa.Column('conclusion_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benchmark_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('problem_id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('repetitions', sa.Integer(), nullable=True),
    sa.Column('warmup_runs', sa.Integer(), nullable=True),
    sa.Column('hardware_info', sa.JSON(), nullable=True),
    sa.Column('total_duration_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiment_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('algorithm_id', sa.String(length=36), nullable=False),
    sa.Column('algorithm_name', sa.String(length=150), nullable=False),
    sa.Column('input_size', sa.Integer(), nullable=False),
    sa.Column('mean_time_ms', sa.Float(), nullable=False),
    sa.Column('memory_kb', sa.Float(), nullable=True),
    sa.Column('std_dev_ms', sa.Float(), nullable=True),
    sa.Column('operations_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('problem_id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=True),
    sa.Column('input_size', sa.Integer(), nullable=False),
    sa.Column('input_characteristics', sa.JSON(), nullable=True),
    sa.Column('optimization_objective', sa.String(length=100), nullable=True),
    sa.Column('recommended_algorithm_id', sa.String(length=36), nullable=False),
    sa.Column('recommended_algorithm_name', sa.String(length=150), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('explanation_points', sa.JSON(), nullable=True),
    sa.Column('scores_breakdown', sa.JSON(), nullable=True),
    sa.Column('runner_ups', sa.JSON(), nullable=True),
    sa.Column('theoretical_analysis', sa.JSON(), nullable=True),
    sa.Column('benchmark_evidence', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benchmark_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('benchmark_run_id', sa.String(length=36), nullable=False),
    sa.Column('algorithm_id', sa.String(length=36), nullable=False),
    sa.Column('algorithm_name', sa.String(length=150), nullable=False),
    sa.Column('input_size', sa.Integer(), nullable=False),
    sa.Column('min_time_ms', sa.Float(), nullable=False),
    sa.Column('max_time_ms', sa.Float(), nullable=False),
    sa.Column('mean_time_ms', sa.Float(), nullable=False),
    sa.Column('median_time_ms', sa.Float(), nullable=False),
    sa.Column('std_dev_time_ms', sa.Float(), nullable=True),
    sa.Column('memory_peak_kb', sa.Float(), nullable=True),
    sa.Column('memory_allocated_kb', sa.Float(), nullable=True),
    sa.Column('comparisons_count', sa.Integer(), nullable=True),
    sa.Column('swaps_count', sa.Integer(), nullable=True),
    sa.Column('recursive_calls_count', sa.Integer(), nullable=True),
    sa.Column('operations_count', sa.Integer(), nullable=True),
    sa.Column('raw_execution_times', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['algorithm_id'], ['algorithms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['benchmark_run_id'], ['benchmark_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('benchmark_results')
    op.drop_table('recommendations')
    op.drop_table('experiment_results')
    op.drop_table('benchmark_runs')
    op.drop_table('experiments')
    op.drop_table('datasets')
    op.drop_table('algorithm_problem_mappings')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_problems_slug'), table_name='problems')
    op.drop_index(op.f('ix_problems_name'), table_name='problems')
    op.drop_index(op.f('ix_problems_category'), table_name='problems')
    op.drop_table('problems')
    op.drop_index(op.f('ix_algorithms_slug'), table_name='algorithms')
    op.drop_index(op.f('ix_algorithms_paradigm'), table_name='algorithms')
    op.drop_index(op.f('ix_algorithms_name'), table_name='algorithms')
    op.drop_index(op.f('ix_algorithms_category'), table_name='algorithms')
    op.drop_table('algorithms')
    # ### end Alembic commands ###
